sudo: false

# Limit clone depth to 5, to speed up build
git:
  depth: 5

# Install Terraform
install:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip

# Perform Terraform validation
script:
  - terraform validate -check-variables=false